service: your-service-name

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: test-url
          method: get

resources:
  Resources:
    DogeBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: new-serverless-framework-deployments-us-east-1-4ca6f522-0f10   # Replace with your bucket name
  Outputs:
    DogeBucketName:
      Value:
        Ref: DogeBucket
      Export:
        Name: DogeBucketName

custom:
  s3Sync:
    - bucketName: new-serverless-framework-deployments-us-east-1-4ca6f522-0f10   # Replace with your bucket name
      localDir: './'  # Ensure 'doge1.jpg' is in this directory

plugins:
  - serverless-s3-sync
